apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.shortLoopControlTower.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.shortLoopControlTower.appName }}
    namespace: {{ .Release.Namespace }}
    draft: {{ default "draft-app" .Values.draft }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: {{ default "50%" .Values.maxSurge }}
      maxUnavailable: {{ default "30%" .Values.maxUnavailable }}
    type: RollingUpdate
  replicas: {{ default "1" .Values.shortLoopControlTower.replicaCount }}
  selector:
    matchLabels:
      app:  {{ .Values.shortLoopControlTower.appName }}
      namespace: {{ .Release.Namespace }}
  template:
    metadata:
      labels:
        draft: {{ default "draft-app" .Values.draft }}
        app:  {{ .Values.shortLoopControlTower.appName }}
        namespace: {{ .Release.Namespace }}
        rollover: {{ default "false" .Values.rollover | quote }}
    spec:
      volumes:
        - name: applogs
          emptyDir: {}
      {{- range $p := .Values.secretFiles }}
        - name: {{ .name }}
          secret:
            secretName: {{ template "name" $ }}-{{ .name }}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.shortLoopControlTower.image.repository }}:{{ .Values.shortLoopControlTower.image.tag }}"
        lifecycle:                   
          preStop:                   
            exec:                    
              command:               
              - sh
              - -c
              - "{{ default "echo Done" .Values.preStopCommand}} && sleep {{ default 120 .Values.drainTime }}"
        imagePullPolicy: {{ .Values.shortLoopControlTower.image.pullPolicy }}
        terminationMessagePath: "/logs/app-name/termination.log"
        terminationMessagePolicy: "FallbackToLogsOnError"
        ports:
        - containerPort: {{ .Values.shortLoopControlTower.exposePort }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.shortLoopControlTower.exposePort }}
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.shortLoopControlTower.exposePort }}
          initialDelaySeconds: 30
          periodSeconds: 15
          successThreshold: 1
          timeoutSeconds: 1
        resources:
        {{ toYaml .Values.resources | indent 12 }}
