apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shortLoopControlTower.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.shortLoopControlTower.appName }}
    namespace: {{ .Release.Namespace }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name }}
  annotations:
  {{ toYaml .annotations | indent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.shortLoopControlTower.exposePort }}
      targetPort: {{ .Values.shortLoopControlTower.exposePort }}
      protocol: TCP
      name: shortloop-ct-http-8080
  selector:
    namespace: {{ .Release.Namespace }}
    app: {{ .Values.shortLoopControlTower.appName }}