shortLoopControlTower:
  appName: shortloop-control-tower
  domainName: xyz.com
  exposePort: 8080
  replicaCount: 1
  image:
    repository: hello-world
    tag: latest
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 100Mi

shortLoopUI:
  appName: shortloop-ui
  domainName: xyz.com
  exposePort: 5000
  replicaCount: 1
  image:
    repository:
    tag:
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 100Mi

terminationGracePeriodSeconds: 120
replicaCount: 1
maxSurge: 30%
maxUnavailable: 10%
pdb:
  minAvailable: 49%
drainTime: 60
preStopCommand: echo Done
rollover: false
