shortLoopControlTower:
  appName: shortloop-control-tower
  domainName: xyz.com
  exposePort: 80
  replicaCount: 1
  image:
    repository: shortloop/control-tower
    tag: 0.0.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 8024Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  dbHost:
  dbPort:
  dbName:
  dbUser:
  dbPwd:
  logDir: /var/log/shortloop
  env: dev
shortLoopUI:
  appName: shortloop-ui
  domainName: xyz.com
  exposePort: 5000
  replicaCount: 1
  postHogKey:
  postHogHost:
  orgName:
  image:
    repository: shortloop/portal
    tag: 0.0.1
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1000m
      memory: 4024Mi
terminationGracePeriodSeconds: 120
replicaCount: 1
maxSurge: 30%
maxUnavailable: 10%
pdb:
  minAvailable: 49%
drainTime: 60
preStopCommand: echo Done
rollover: false
