apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.shortLoopControlTower.appName }}
  namespace: {{ .Release.Namespace }}
  labels:
  app: {{ template "name" . }}
  app.kubernetes.io/name: {{ template "name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
  {{ toYaml .annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.shortLoopControlTower.exposePort }}
      targetPort: {{ .Values.shortLoopControlTower.exposePort }}
      protocol: TCP
      name: shortloop-ct-http-8080
selector:
  namespace: {{ .Release.Namespace }}
  app: {{ template "name" . }}