version: '2'
services:
  shortloop-control-tower-with-external-db:
    profiles: ["external-db"]
    image: shortloop/control-tower:0.0.6
    container_name: shortloop
    volumes:
      - shortloop-logs:/var/log/shortloop
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - SENTRY_DSN=${SENTRY_DSN}
      - LOG_DIR=/var/log/shortloop
      - ANALYTICS_KEY=${ANALYTICS_KEY:?ANALYTICS_KEY is mandatory in environment. Ask Shortloop to provide this.}
      - ANALYTICS_HOST=https://app.posthog.com
      - ORG_NAME=${ORG_NAME?:ORG_NAME is mandatory field in environment. Please fill in the .env (or .env-local.db) file}
      - ENV=prod
    ports:
      - ${SHORTLOOP_PORT:-80}:8080
  shortloop-control-tower-with-self-db:
    profiles: ["self-db"]
    image: shortloop/control-tower:0.0.6
    container_name: shortloop
    volumes:
      - shortloop-logs:/var/log/shortloop
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=shortloop
      - DB_USER=shortloop
      - DB_PWD=shortloop
      - SENTRY_DSN=${SENTRY_DSN}
      - LOG_DIR=/var/log/shortloop
      - ANALYTICS_KEY=${ANALYTICS_KEY:?ANALYTICS_KEY is mandatory in environment. Ask Shortloop to provide this.}
      - ANALYTICS_HOST=https://app.posthog.com
      - ORG_NAME=${ORG_NAME?:ORG_NAME is mandatory field in environment. Please fill in the .env (or .env-local.db) file}
      - ENV=prod
    ports:
      - ${SHORTLOOP_PORT:-80}:8080
    depends_on:
      - postgres
  postgres:
    profiles: ["self-db"]
    image: postgres:14.6
    container_name: postgres
    environment:
      - POSTGRES_USER=shortloop
      - POSTGRES_PASSWORD=shortloop
      - POSTGRES_DB=shortloop
    ports:
      - 5432:5432
    volumes:
      - shortloop-postgres-volume:/var/lib/postgresql/data
    shm_size: 256MB 

volumes:
    shortloop-logs-fe:
        external: false
    shortloop-postgres-volume:
        external: false
    shortloop-logs:
        external: false